# Generated by Django 3.2.3 on 2021-08-07 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_room_current_song'),
        ('spotify', '0002_voteduser'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VotedUser',
            new_name='Vote',
        ),
    ]
